/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cnambition_ultrasonic_thread_MyAudio */

#ifndef _Included_com_cnambition_ultrasonic_thread_MyAudio
#define _Included_com_cnambition_ultrasonic_thread_MyAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    NativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_NativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    Init
 * Signature: (ZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_Init
  (JNIEnv *, jobject, jboolean, jstring);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_Release
  (JNIEnv *, jobject);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    AddOrReleaseUser
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_AddOrReleaseUser
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    ClientingListNonEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_ClientingListNonEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    ClientingListEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_ClientingListEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    ReceiveAuBuffer
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_ReceiveAuBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_cnambition_ultrasonic_thread_MyAudio
 * Method:    GetAuSendData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cnambition_ultrasonic_thread_MyAudio_GetAuSendData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif